# Web
spring:
  messages:
    basename: messages/messages
  thymeleaf:
    mode: HTML
logging:
  level:
    org:
      springframework: INFO

---
spring:
  profiles: dev
management:
  endpoints:
    web:
      exposure:
        include: *